-- MySQL Script generated by MySQL Workbench
-- Fri Sep 23 00:25:52 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoetb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoetb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoetb` DEFAULT CHARACTER SET utf8 ;
USE `projetoetb` ;

-- -----------------------------------------------------
-- Table `projetoetb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetoetb`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `dataCadastro` DATE NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
